### ISSUE TITLE
Route with direct instances and  specific method of instance

### ISSUE THREAD

**Issue by brenodouglas** [Respect/Rest#117]
I always have the need to get a sub feature of a specific resource, eg houses a specific person /person/1/homes and as always come and always used method Any passing instances of Routable missed being able to spend a GET, POST, etc. specifying the method as in the next example:

```php
class Person implements \Respect\Rest\Routable
{
    public function homes($id) {
        return json_encode(['house1', 'hous2'];
    }
}

$person = new Person();
$r3 = new Router();
$r3->get("/person/*/homes", $person, 'homes');
```

I did a fork of Respect/Rest and made the change that was nothing complicated  and it worked perfectly.

My question is only if you already have some feature so being implemented? And if my need is valid for anyone else?

**Comment by HwapX** [comment]
+1
meanwhile you can do something like this:

```php
function wrapIntoClosure($callable) {
	return function() use($callable) {
		return call_user_func_array($callable, func_get_args());
	};
}

class Person
{
    public function homes($id) {
        return json_encode(['house1', 'hous2'];
    }
}

$person = new Person();
$r3 = new Router();
$r3->get("/person/*/homes", wrapIntoClosure(array($person, 'home')));
```
it work with any valid php [callable](http://php.net/manual/en/language.types.callable.php)..

**Comment by augustohp** [comment]
As we support [any callable](http://php.net/manual/en/language.types.callable.php), you can do the following:

```php
class Pages
{
    public function index($name = 'World')
    {
        return sprintf('Hello %s!', $name);
    }
}

$pages = new Pages;

$app = new Respect\Rest\Router;
$app->get('/', array($pages, 'index'));
$app->get('/*', array($pages, 'index'));
```

Please note that you don't need to implement the `Routable` interface and neither wrap you instance into a closure.

I will close the issue but please, feel free to open it again.
