### ISSUE TITLE
Can I Somehow Nest Routers?

### ISSUE THREAD

**Issue by m42e** [Respect/Rest#118]
Hi,

Is it possible to concat routers, e.g. having a router, that handles 'image/*/*' and 'text/*'. And another router handling 'history/*'. 

Can I have a router that handles 'history/*/image/*/*' and 'history/*/text/*' by nesting the routers somehow?

Thanks for any hint how to deal with that easily.

**Comment by williamespindola** [comment]
Something like this?
```php
$r3->get(array('/history/image/*', '/history/text/*'), function($id) {
    return 'History ' . $id;
});
```
[Multiple Routes](https://github.com/Respect/Rest/blob/master/docs/README.md#multiple-routes)

**Comment by m42e** [comment]
Ok, I actually found a solution, as I'm writing this response here.

```php
$myGetImage = function($id, $hitory = null){...}
$r3->get('/image/*', $myGetImage);                                                                                                                                                                                                            
$r3->get('/history/*/image/*', function($history, $id) use($myGetImage){                                                                
     return $myGetImage($id, $history);                                                                                                
});     
```
