### ISSUE TITLE
PHP7.3: preg_replace(): Compilation failed: invalid range in character class at offset 8

### ISSUE THREAD

**Issue by sokolnikov911** [Respect/Rest#135]
On PHP7.3 I have got next error: 

`preg_replace(): Compilation failed: invalid range in character class at offset 8`

In respect/rest/library/Respect/Rest/Routes/AbstractRoute.php(222)

**Comment by sokolnikov911** [comment]
I have fixed it on PR: https://github.com/Respect/Rest/pull/136

**Comment by nickl-** [comment]
Closed: #136 has been merged
