### ISSUE TITLE
Are we there yet? I want to go PHP 5.4.... Are we there yet?

### ISSUE THREAD

**Issue by nickl-** [Respect/Rest#81]
I am sure we all know being irritating to our parents, repeatedly asking "are we there yet" when on long road trips, does this ring a bell? Some of us have already experienced this from the other end of the stick or will soon be. Myself and @alganet  as far as I know, are not close to that so allow me to experience the child within as you will be hearing me say this frequently:

# Are we there yet?

Since we've recently been prive to a release of 5.5.alpha1 is this a good enough excuse to bump the minimum requirement already? If you think it's too early still I have only one thing to say: with puppydog face...

### But what about generators? 

We can't exactly go skip a version PHP or can we? ...and I can't start irritating you with...

# Are we there yet? 

...for wanting to use yield and send and... anyway...

# Are we there yet?

Would it be allright... is it acceptable... would anyone complain profusely or go tell the parents if I do? =) 

# Are we there yet?

I actually have a legitimate reason as argument, premise, good excuse to justify the move.  One of the big gripes we had, amongst others, with implementing #28 was the fact that PHP had no support for status codes and while I have been thinking, even implemented some, alternative approaches to the array collection with code to reason mappings, as you may know PHP 5.4 came with support for:

**[http_response_code](http://www.php.net/manual/en/function.http-response-code.php)**

Need I say more?I think the topic is well documented already. Now it's true we could polyfill [backward compatibility](http://www.php.net/manual/en/function.http-response-code.php#107261) but eeeuuww and what about [array short syntax](http://php.net/manual/en/language.types.array.php#example-82) we can't exactly stub that compatible. The sooner we're done with 5.4 the sooner we can move to 5.5 \o/ so one more time:

# Are we there yet, already?

**Comment by augustohp** [comment]
I am closing this, although I am always eager to move forward into version requirements I would not likely do so just for the sake of it.

If we ever need to update the version, we should do so in that occasion.
