### ISSUE TITLE
Autodetect Path

### ISSUE THREAD

**Issue by blindsamson** [Respect/Rest#93]
Hi guys, 

Came across something today when moving between different servers. Currently you must declare the script path as such:
```php
    $router = new Router("/blindsamson/dev/rest");
```

I threw something together and was wondering if it's make sense to make this easier to do out of the box.

This was my first implementation:
```php
    $script_path = explode("/", $_SERVER["SCRIPT_NAME"]);
    unset($script_path[count($script_path) - 1]);
    $script_path = implode("/", $script_path);

    $router = new Router($script_path);
```

And to make it a one-liner I went with: 
```php
    $script_path = str_replace($_SERVER["DOCUMENT_ROOT"], "", dirname(__FILE__));
```

Thoughts? Or is there a better way to do this?

**Comment by augustohp** [comment]
One can always instantiate with `Respect\Rest\Router($_SERVER["DOCUMENT_ROOT"])` as well and there are times when the *document root* is not what one expects to be interpreted to be actually what the routes are going to be resolved against.
